from .start import start
from .colosseum import colosseum
from .dungeon import dungeon
from .other_dungeon import other_dungeon
from .spectator_entrance import spectator_entrance
from .market import market
from .slums import slums
from .rich import rich
from .kings_entrance import kings_entrance
from .stairs import stairs
from .kings_hall import kings_hall
from .guard_quarters import guard_quarters
from .kings_quarters import kings_quarters
from .kings_bath import kings_bath
from .nymph_passage import nymph_passage
from .troll_room import troll_room
from .riddle_door import riddle_door
from .witch_tower import witch_tower
from .weapons_chamber import weapons_chamber
from .dragonhold import dragonhold
from .hall import hall
from .four_seasons_room import four_seasons_room
from .room_o_doom import room_o_doom
from .exit import exit
from .dead import dead
from .win_dragon import win_dragon
from .win_witch import win_witch
from .win_cowardly import win_cowardly